name: Fabricator
version: 1.0
main: com.newestaf.fabricator.Fabricator
api-version: 1.20
commands:
  fabricator:
    description: Opens the fabricator inventory
    usage: /fabricator <open>
    aliases: [fab]
